// Code generated by ent, DO NOT EDIT.

package model

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/itsabgr/authz/db/model/authz"
)

// AuthzCreate is the builder for creating a Authz entity.
type AuthzCreate struct {
	config
	mutation *AuthzMutation
	hooks    []Hook
}

// SetUser sets the "user" field.
func (ac *AuthzCreate) SetUser(s string) *AuthzCreate {
	ac.mutation.SetUser(s)
	return ac
}

// SetRelation sets the "relation" field.
func (ac *AuthzCreate) SetRelation(s string) *AuthzCreate {
	ac.mutation.SetRelation(s)
	return ac
}

// SetEntity sets the "entity" field.
func (ac *AuthzCreate) SetEntity(s string) *AuthzCreate {
	ac.mutation.SetEntity(s)
	return ac
}

// SetExpireAt sets the "expire_at" field.
func (ac *AuthzCreate) SetExpireAt(t time.Time) *AuthzCreate {
	ac.mutation.SetExpireAt(t)
	return ac
}

// SetNillableExpireAt sets the "expire_at" field if the given value is not nil.
func (ac *AuthzCreate) SetNillableExpireAt(t *time.Time) *AuthzCreate {
	if t != nil {
		ac.SetExpireAt(*t)
	}
	return ac
}

// SetCreatedAt sets the "created_at" field.
func (ac *AuthzCreate) SetCreatedAt(t time.Time) *AuthzCreate {
	ac.mutation.SetCreatedAt(t)
	return ac
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ac *AuthzCreate) SetNillableCreatedAt(t *time.Time) *AuthzCreate {
	if t != nil {
		ac.SetCreatedAt(*t)
	}
	return ac
}

// Mutation returns the AuthzMutation object of the builder.
func (ac *AuthzCreate) Mutation() *AuthzMutation {
	return ac.mutation
}

// Save creates the Authz in the database.
func (ac *AuthzCreate) Save(ctx context.Context) (*Authz, error) {
	ac.defaults()
	return withHooks(ctx, ac.sqlSave, ac.mutation, ac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ac *AuthzCreate) SaveX(ctx context.Context) *Authz {
	v, err := ac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ac *AuthzCreate) Exec(ctx context.Context) error {
	_, err := ac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ac *AuthzCreate) ExecX(ctx context.Context) {
	if err := ac.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ac *AuthzCreate) defaults() {
	if _, ok := ac.mutation.CreatedAt(); !ok {
		v := authz.DefaultCreatedAt()
		ac.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ac *AuthzCreate) check() error {
	if _, ok := ac.mutation.User(); !ok {
		return &ValidationError{Name: "user", err: errors.New(`model: missing required field "Authz.user"`)}
	}
	if _, ok := ac.mutation.Relation(); !ok {
		return &ValidationError{Name: "relation", err: errors.New(`model: missing required field "Authz.relation"`)}
	}
	if _, ok := ac.mutation.Entity(); !ok {
		return &ValidationError{Name: "entity", err: errors.New(`model: missing required field "Authz.entity"`)}
	}
	if _, ok := ac.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`model: missing required field "Authz.created_at"`)}
	}
	return nil
}

func (ac *AuthzCreate) sqlSave(ctx context.Context) (*Authz, error) {
	if err := ac.check(); err != nil {
		return nil, err
	}
	_node, _spec := ac.createSpec()
	if err := sqlgraph.CreateNode(ctx, ac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	ac.mutation.id = &_node.ID
	ac.mutation.done = true
	return _node, nil
}

func (ac *AuthzCreate) createSpec() (*Authz, *sqlgraph.CreateSpec) {
	var (
		_node = &Authz{config: ac.config}
		_spec = sqlgraph.NewCreateSpec(authz.Table, sqlgraph.NewFieldSpec(authz.FieldID, field.TypeInt))
	)
	if value, ok := ac.mutation.User(); ok {
		_spec.SetField(authz.FieldUser, field.TypeString, value)
		_node.User = value
	}
	if value, ok := ac.mutation.Relation(); ok {
		_spec.SetField(authz.FieldRelation, field.TypeString, value)
		_node.Relation = value
	}
	if value, ok := ac.mutation.Entity(); ok {
		_spec.SetField(authz.FieldEntity, field.TypeString, value)
		_node.Entity = value
	}
	if value, ok := ac.mutation.ExpireAt(); ok {
		_spec.SetField(authz.FieldExpireAt, field.TypeTime, value)
		_node.ExpireAt = &value
	}
	if value, ok := ac.mutation.CreatedAt(); ok {
		_spec.SetField(authz.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// AuthzCreateBulk is the builder for creating many Authz entities in bulk.
type AuthzCreateBulk struct {
	config
	err      error
	builders []*AuthzCreate
}

// Save creates the Authz entities in the database.
func (acb *AuthzCreateBulk) Save(ctx context.Context) ([]*Authz, error) {
	if acb.err != nil {
		return nil, acb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(acb.builders))
	nodes := make([]*Authz, len(acb.builders))
	mutators := make([]Mutator, len(acb.builders))
	for i := range acb.builders {
		func(i int, root context.Context) {
			builder := acb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AuthzMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, acb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, acb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, acb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (acb *AuthzCreateBulk) SaveX(ctx context.Context) []*Authz {
	v, err := acb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (acb *AuthzCreateBulk) Exec(ctx context.Context) error {
	_, err := acb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (acb *AuthzCreateBulk) ExecX(ctx context.Context) {
	if err := acb.Exec(ctx); err != nil {
		panic(err)
	}
}
