// Code generated by ent, DO NOT EDIT.

package model

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/itsabgr/authz/db/model/authz"
)

// Authz is the model entity for the Authz schema.
type Authz struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// User holds the value of the "user" field.
	User string `json:"user,omitempty"`
	// Relation holds the value of the "relation" field.
	Relation string `json:"relation,omitempty"`
	// Entity holds the value of the "entity" field.
	Entity string `json:"entity,omitempty"`
	// ExpireAt holds the value of the "expire_at" field.
	ExpireAt *time.Time `json:"expire_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Authz) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case authz.FieldID:
			values[i] = new(sql.NullInt64)
		case authz.FieldUser, authz.FieldRelation, authz.FieldEntity:
			values[i] = new(sql.NullString)
		case authz.FieldExpireAt, authz.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Authz fields.
func (a *Authz) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case authz.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			a.ID = int(value.Int64)
		case authz.FieldUser:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user", values[i])
			} else if value.Valid {
				a.User = value.String
			}
		case authz.FieldRelation:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field relation", values[i])
			} else if value.Valid {
				a.Relation = value.String
			}
		case authz.FieldEntity:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field entity", values[i])
			} else if value.Valid {
				a.Entity = value.String
			}
		case authz.FieldExpireAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expire_at", values[i])
			} else if value.Valid {
				a.ExpireAt = new(time.Time)
				*a.ExpireAt = value.Time
			}
		case authz.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				a.CreatedAt = value.Time
			}
		default:
			a.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Authz.
// This includes values selected through modifiers, order, etc.
func (a *Authz) Value(name string) (ent.Value, error) {
	return a.selectValues.Get(name)
}

// Update returns a builder for updating this Authz.
// Note that you need to call Authz.Unwrap() before calling this method if this Authz
// was returned from a transaction, and the transaction was committed or rolled back.
func (a *Authz) Update() *AuthzUpdateOne {
	return NewAuthzClient(a.config).UpdateOne(a)
}

// Unwrap unwraps the Authz entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (a *Authz) Unwrap() *Authz {
	_tx, ok := a.config.driver.(*txDriver)
	if !ok {
		panic("model: Authz is not a transactional entity")
	}
	a.config.driver = _tx.drv
	return a
}

// String implements the fmt.Stringer.
func (a *Authz) String() string {
	var builder strings.Builder
	builder.WriteString("Authz(")
	builder.WriteString(fmt.Sprintf("id=%v, ", a.ID))
	builder.WriteString("user=")
	builder.WriteString(a.User)
	builder.WriteString(", ")
	builder.WriteString("relation=")
	builder.WriteString(a.Relation)
	builder.WriteString(", ")
	builder.WriteString("entity=")
	builder.WriteString(a.Entity)
	builder.WriteString(", ")
	if v := a.ExpireAt; v != nil {
		builder.WriteString("expire_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(a.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Authzs is a parsable slice of Authz.
type Authzs []*Authz
