// Code generated by ent, DO NOT EDIT.

package model

import (
	"time"

	"github.com/itsabgr/authz/db/model/authz"
	"github.com/itsabgr/authz/db/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	authzFields := schema.Authz{}.Fields()
	_ = authzFields
	// authzDescCreatedAt is the schema descriptor for created_at field.
	authzDescCreatedAt := authzFields[4].Descriptor()
	// authz.DefaultCreatedAt holds the default value on creation for the created_at field.
	authz.DefaultCreatedAt = authzDescCreatedAt.Default.(func() time.Time)
}
