// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AuthzColumns holds the columns for the "authz" table.
	AuthzColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "user", Type: field.TypeString},
		{Name: "relation", Type: field.TypeString},
		{Name: "entity", Type: field.TypeString},
		{Name: "expire_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// AuthzTable holds the schema information for the "authz" table.
	AuthzTable = &schema.Table{
		Name:       "authz",
		Columns:    AuthzColumns,
		PrimaryKey: []*schema.Column{AuthzColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "authz_user_relation_entity",
				Unique:  true,
				Columns: []*schema.Column{AuthzColumns[1], AuthzColumns[2], AuthzColumns[3]},
			},
			{
				Name:    "authz_expire_at_user_relation_entity",
				Unique:  false,
				Columns: []*schema.Column{AuthzColumns[4], AuthzColumns[1], AuthzColumns[2], AuthzColumns[3]},
			},
			{
				Name:    "authz_expire_at",
				Unique:  false,
				Columns: []*schema.Column{AuthzColumns[4]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AuthzTable,
	}
)

func init() {
}
